// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Eul Bite

//! Cross-repository evidence contract. The fixture is generated by the closed
//! Spine producer (`examples/generate_public_evidence_vectors.rs`) and consumed
//! here without sharing implementation code.

use serde::Deserialize;
use spine_core::{
    verify_audit_pack, verify_checkpoint_history, AuditPackPolicy, AuditPackV1,
    CheckpointReceiptV2, CheckpointTrustPolicy, TrustedWitness,
};

const NOW_NS: i64 = 1_780_000_063_000_000_000;

#[derive(Clone, Deserialize)]
struct EvidenceVectors {
    schema_version: u32,
    operator_initial_public_key: String,
    operator_rotated_public_key: String,
    witness_id: String,
    witness_public_key: String,
    tenant_id: String,
    checkpoint_history: Vec<CheckpointReceiptV2>,
    audit_pack: AuditPackV1,
}

fn vectors() -> EvidenceVectors {
    serde_json::from_str(include_str!("../../test-vectors/evidence-vectors.json"))
        .expect("server-generated evidence vectors must parse")
}

fn checkpoint_policy(vectors: &EvidenceVectors) -> CheckpointTrustPolicy {
    CheckpointTrustPolicy {
        initial_operator_public_key: vectors.operator_initial_public_key.clone(),
        trusted_witness: Some(TrustedWitness {
            witness_id: vectors.witness_id.clone(),
            public_key: vectors.witness_public_key.clone(),
        }),
        allow_unwitnessed: false,
        expected_chain_id: Some("primary-eu".into()),
        now_ns: Some(NOW_NS),
        max_age_secs: Some(120),
    }
}

fn audit_policy(vectors: &EvidenceVectors) -> AuditPackPolicy {
    AuditPackPolicy {
        expected_tenant_id: vectors.tenant_id.clone(),
        checkpoint_policy: checkpoint_policy(vectors),
    }
}

#[test]
fn server_generated_history_verifies_through_rotation_and_witness() {
    let vectors = vectors();
    assert_eq!(vectors.schema_version, 1);
    let report =
        verify_checkpoint_history(&vectors.checkpoint_history, &checkpoint_policy(&vectors))
            .expect("public verifier must accept the server-generated history");
    assert_eq!(report.checkpoint_count, 2);
    assert_eq!(
        report.established_operator_public_key,
        vectors.operator_rotated_public_key
    );
    assert_eq!(report.trusted_witness_observations, 2);
    assert_eq!(report.last_sequence, 3);
}

#[test]
fn server_generated_tenant_audit_pack_verifies() {
    let vectors = vectors();
    let report = verify_audit_pack(&vectors.audit_pack, &audit_policy(&vectors))
        .expect("public verifier must accept the server-generated audit pack");
    assert_eq!(report.tenant_event_count, 2);
    assert_eq!(report.proof_checkpoint_count, 2);
    assert_eq!(report.selected_interval_count, 2);
}

#[test]
fn external_pins_cannot_be_replaced_by_embedded_keys() {
    let vectors = vectors();
    let mut policy = checkpoint_policy(&vectors);
    policy.initial_operator_public_key = vectors.operator_rotated_public_key.clone();
    assert!(verify_checkpoint_history(&vectors.checkpoint_history, &policy).is_err());

    let mut witness_policy = checkpoint_policy(&vectors);
    witness_policy
        .trusted_witness
        .as_mut()
        .expect("fixture has a witness")
        .public_key = vectors.operator_initial_public_key.clone();
    assert!(verify_checkpoint_history(&vectors.checkpoint_history, &witness_policy).is_err());
}

#[test]
fn tampered_rotation_witness_and_checkpoint_link_are_rejected() {
    let vectors = vectors();

    let mut rotation = vectors.checkpoint_history.clone();
    rotation[1]
        .core
        .key_transition
        .as_mut()
        .expect("fixture rotates")
        .reason = "attacker-selected".into();
    assert!(verify_checkpoint_history(&rotation, &checkpoint_policy(&vectors)).is_err());

    let mut witness = vectors.checkpoint_history.clone();
    witness[1].witnesses[0].observed_at_ns += 1;
    assert!(verify_checkpoint_history(&witness, &checkpoint_policy(&vectors)).is_err());

    let mut link = vectors.checkpoint_history.clone();
    link[1].core.previous_checkpoint_id = Some("00".repeat(32));
    assert!(verify_checkpoint_history(&link, &checkpoint_policy(&vectors)).is_err());
}

#[test]
fn audit_pack_omission_and_wrong_tenant_are_rejected() {
    let vectors = vectors();
    let mut omitted = vectors.audit_pack.clone();
    omitted.intervals[0].events.clear();
    assert!(verify_audit_pack(&omitted, &audit_policy(&vectors)).is_err());

    let mut wrong_tenant = audit_policy(&vectors);
    wrong_tenant.expected_tenant_id = "tenant-b".into();
    assert!(verify_audit_pack(&vectors.audit_pack, &wrong_tenant).is_err());
}

#[test]
fn signed_fields_require_canonical_lowercase_hex() {
    let vectors = vectors();
    let mut history = vectors.checkpoint_history.clone();
    history[0].checkpoint_id = history[0].checkpoint_id.to_ascii_uppercase();
    assert!(verify_checkpoint_history(&history, &checkpoint_policy(&vectors)).is_err());
}

#[test]
fn witness_policy_rejects_future_stale_and_duplicate_observations() {
    let vectors = vectors();

    let mut future = checkpoint_policy(&vectors);
    future.now_ns = Some(1_780_000_000_500_000_000);
    future.max_age_secs = None;
    assert!(verify_checkpoint_history(&vectors.checkpoint_history, &future).is_err());

    let mut stale = checkpoint_policy(&vectors);
    stale.now_ns = Some(1_780_000_182_000_000_001);
    stale.max_age_secs = Some(120);
    assert!(verify_checkpoint_history(&vectors.checkpoint_history, &stale).is_err());

    let mut duplicate = vectors.checkpoint_history.clone();
    let repeated_witness = duplicate[0].witnesses[0].clone();
    duplicate[0].witnesses.push(repeated_witness);
    assert!(verify_checkpoint_history(&duplicate, &checkpoint_policy(&vectors)).is_err());
}

#[test]
fn operator_only_verification_requires_an_explicit_policy_downgrade() {
    let vectors = vectors();
    let mut refused = checkpoint_policy(&vectors);
    refused.trusted_witness = None;
    assert!(verify_checkpoint_history(&vectors.checkpoint_history, &refused).is_err());

    refused.allow_unwitnessed = true;
    assert!(verify_checkpoint_history(&vectors.checkpoint_history, &refused).is_ok());
}
